### ISSUE TITLE
Support for using Local Lan protocol

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30api#11]
The current IOS App is able to communicate with the thermostat using the DDS protocol.  It would be good to extend the API to support local LAN communication.

**Comment by dresslerc** [comment]
How do you know the iOS app supports this local communication?  The Lennox S30 app has been horrible.  The HomeKit implementation works local but doesn’t support zones

**Comment by PeteRager** [comment]
> How do you know the iOS app supports this local communication? The Lennox S30 app has been horrible. The HomeKit implementation works local but doesn’t support zones

I observed the RTPS/OpenDDS traffic between the IOS device and thermostat in wireshark

**Comment by HyperActiveJ** [comment]
Suggestion: Time to update the name and README to include local!

**Comment by AirborneEagle** [comment]
This is probably the wrong place to ask this question, and I am happy to move to a forum you recommend . @PeteRager 
Forgive my lack of basic system knowledge.
My goal here is to actually eliminate the lennox on-wall thermostats (s40) entirely. I am happy to implement any control protocol needed to do so. Dry contacts, analog signals, Modbus, Network calls, etc. Anything.  Any Idea if this is possible?

If not, the next acceptable option would be to use your amazing integration, but it would be with a different software (Loxone Config). 
Would you be willing to offer any assistance in applying the API to a different use case? 
Or perhaps we could work to extract the API structure, parameters, documentation etc. into a template so that it can be more easily used by things other than HA?

**Comment by PeteRager** [comment]
Probably a good set of questions for a discussion here https://github.com/PeteRager/lennoxs30api/discussions
